comments = [
    "The steak was cooked to perfection, absolutely delicious!",
    "Service was slow, but the food was decent.",
    "Terrible experience, will never come back.",
    "The atmosphere was nice, but the food was just okay.",
    "Best restaurant in town, everything was fantastic!",
    "Mediocre food, nothing special.",
    "The waiter was rude and the food was cold.",
    "Great value for money, large portions and tasty food.",
    "The restaurant was too noisy, couldn't enjoy my meal.",
    "Fresh ingredients and innovative dishes, loved it!",
    "Overpriced for what you get.",
    "The dessert was heavenly, but the main course was average.",
    "Friendly staff and cozy ambiance.",
    "Food was bland and uninspired.",
    "Quick service and decent food, good for a quick lunch.",
    "The seafood tasted off, wouldn't recommend.",
    "Beautiful presentation, but flavors were lacking.",
    "Authentic cuisine, felt like I was in Italy!",
    "The restaurant was dirty and the food was greasy.",
    "Impeccable service and exquisite flavors.",
    "Just another average dining experience.",
    "The chef's special was a disappointment.",
    "Cozy atmosphere, perfect for a date night.",
    "Overcooked meat and underseasoned vegetables.",
    "The wine list was impressive, complemented the food well.",
    "Slow service ruined an otherwise okay meal.",
    "Innovative fusion cuisine, a treat for the taste buds!",
    "The portions were tiny for the price.",
    "Fresh sushi and attentive staff.",
    "Bland and boring, nothing stood out.",
    "The vegetarian options were creative and delicious.",
    "Uncomfortable seating and mediocre food.",
    "The breakfast buffet had something for everyone.",
    "Overpriced and pretentious, style over substance.",
    "Comforting home-style cooking, just like grandma used to make.",
    "The restaurant was understaffed and it showed in the service.",
    "Delightful flavors and beautiful plating.",
    "The food was edible, but nothing to write home about.",
    "Excellent gluten-free options, felt catered to.",
    "Disappointing experience overall, won't be returning.",
    "The cocktails were innovative and paired well with the appetizers.",
    "Average food, but the view from the restaurant was spectacular.",
    "Unfriendly staff and mediocre food, not worth the visit.",
    "The tasting menu was a culinary journey, each course better than the last.",
    "Decent food but overpriced for what you get.",
    "The ambiance was lovely, but the food didn't live up to expectations.",
    "Fast service and tasty food, great for a quick bite.",
    "The food was a letdown, expected much better based on reviews.",
    "Charming little place with delicious homemade pasta.",
    "Unimpressive food and poor value for money.",
    "The flavors were bold and exciting, a real treat for the palate.",
    "Waited an hour for mediocre food, not worth it.",
    "Cozy cafe with decent coffee and pastries.",
    "The pizza was soggy and lacked flavor.",
    "Exceptional customer service made up for the average food.",
    "Overcooked pasta and watery sauce, disappointed.",
    "The brunch menu offered a great variety of options.",
    "Dirty utensils and unappetizing presentation.",
    "The rooftop bar had amazing views and delicious appetizers.",
    "Bland curry, lacked the authentic spices I was expecting.",
    "Family-friendly restaurant with a good kids menu.",
    "The salad was wilted and the dressing was too sour.",
    "Trendy spot with Instagram-worthy dishes that actually taste good.",
    "Lukewarm food served on cold plates, not impressed.",
    "The chef's tasting menu was a delightful surprise.",
    "Overhyped restaurant, didn't live up to expectations.",
    "Quaint bistro with a charming atmosphere and tasty specials.",
    "The steak was tough and flavorless, not worth the price.",
    "Impressive wine pairing enhanced the dining experience.",
    "The service was painfully slow, ruined our evening.",
    "Creative vegan options that could satisfy any meat-eater.",
    "The fish dish smelled off, couldn't bring myself to eat it.",
    "Attentive staff and a diverse menu catering to all dietary needs.",
    "Noisy environment and cramped seating, couldn't relax.",
    "The dessert platter was a work of art, both visually and in taste.",
    "Overpriced and underwhelming, style over substance.",
    "Farm-to-table freshness evident in every bite.",
    "The chicken was dry and the vegetables were overcooked.",
    "Friendly neighborhood spot with consistently good food.",
    "Greasy appetizers and flat soda, won't be coming back.",
    "The seasonal menu showcased local ingredients beautifully.",
    "Poorly executed fusion cuisine, flavors clashed terribly.",
    "Elegant fine dining experience with impeccable service.",
    "The burger was burnt and the fries were soggy.",
    "Cozy pub with great craft beers and decent bar food.",
    "Bland and uninspired menu, lacked creativity.",
    "The breakfast sandwich was the perfect start to my day.",
    "Disorganized service and lukewarm food, disappointing experience.",
    "Hidden gem with authentic ethnic cuisine and friendly staff.",
    "Overcooked seafood and bland rice, not worth the price.",
    "Relaxing cafe with a nice selection of teas and light bites.",
    "The soup was too salty and the bread was stale.",
    "Impressive molecular gastronomy, a feast for the senses.",
    "Chaotic atmosphere and mediocre food, wouldn't recommend.",
    "Delightful afternoon tea service with delicate pastries.",
    "The risotto was undercooked and lacked flavor.",
    "Vibrant food truck with unique and tasty fusion tacos.",
    "Subpar ingredients and poor preparation, a real letdown.",
    "Charming patisserie with exquisite French pastries.",
    "The hot pot was bland and the meat was tough.",
    "Innovative plant-based dishes that could convert any carnivore.",
    "Disappointing dim sum, have had better from frozen packages.",
    "The dim sum was authentic and delicious.",
"Average Thai food, nothing stood out.",
"Terrible pizza, soggy crust and bland toppings.",
"The steak was cooked perfectly, but sides were lackluster.",
"Exceptional farm-to-table experience. Every dish was a knockout!",
"The sushi rolls were creative but lacked flavor.",
"Worst service I've ever experienced. Food was cold too.",
"Great atmosphere and even better food. A local gem!",
"Too loud to hear my dinner companion. Food was just okay.",
"Innovative molecular gastronomy. A feast for all senses!",
"The pasta was overcooked and the sauce was watery.",
"Decent coffee but the breakfast options were limited.",
"Impeccable service made up for the average food.",
"Boring menu, same old options you see everywhere.",
"Quick and tasty, perfect for a lunch break.",
"The fish smelled off, couldn't bring myself to eat it.",
"Beautifully presented dishes, but flavors were muted.",
"Authentic Mexican street food. Felt like I was in Mexico City!",
"Sticky tables and greasy cutlery. Hygiene is clearly not a priority.",
"Michelin-worthy tasting menu. Each course was a masterpiece.",
"Just another generic chain restaurant experience.",
"The signature dish was underwhelming and overpriced.",
"Cozy ambiance, perfect for a casual date night.",
"Overcooked burger and soggy fries. How do you mess that up?",
"Impressive craft beer selection that paired well with the food.",
"45-minute wait for a table, then another hour for food. Not worth it.",
"Fusion cuisine done right. Unexpected flavor combinations that worked!",
"Minuscule portions at astronomical prices. Left hungry and poor.",
"Fresh, high-quality ingredients. You can taste the difference!",
"Uninspired menu and bland execution. Nothing memorable.",
"Excellent vegan options that could satisfy any palate.",
"Cramped seating and slow service ruined the experience.",
"The breakfast platter had something for everyone. Great value!",
"All style, no substance. Instagram-worthy but tasteless.",
"Hearty, homestyle cooking that warmed the soul.",
"Disorganized staff and chaotic atmosphere. Stressful dining experience.",
"Culinary artistry on every plate. A gastronomic delight!",
"The food was passable but nothing special.",
"Extensive allergy-friendly menu. Felt safe and cared for!",
"One of the worst meals I've had in years. Avoid at all costs.",
"Creative cocktail menu with perfect food pairings.",
"Mediocre food saved by the stunning oceanfront view.",
"Condescending staff and disappointing food. Never again.",
"Each course of the chef's menu told a story. Unforgettable!",
"Slightly overpriced for the quality, but not terrible.",
"Promising menu let down by poor execution.",
"Fast-casual done right. Quality ingredients and efficient service.",
"Pretentious atmosphere and underwhelming food. Emperor's new clothes.",
"Charming family-run restaurant with delicious homemade pasta.",
"Forgettable experience. Neither good nor terrible, just bland.",
"The ramen broth was rich and flavorful. Noodles were perfect.",
"Standard diner fare. Nothing to complain about, nothing to rave about.",
"Inedible food and rude staff. Worst dining experience ever.",
"Nice ambiance, but the food was rather forgettable.",
"Mind-blowing flavors! Each dish was better than the last.",
"The tacos were okay, but I've had better street food.",
"Overcooked steak and cold sides. How disappointing.",
"Fantastic value. Large portions of delicious food at great prices.",
"Too cramped and noisy. Couldn't enjoy the meal at all.",
"Farm-fresh ingredients transformed into culinary masterpieces.",
"The risotto was undercooked and lacked seasoning.",
"Decent sandwiches, but the coffee was bitter.",
"Attentive service made the evening special, despite average food.",
"Limited menu with no vegetarian options. Needs improvement.",
"Efficient service and tasty food. Solid lunch spot.",
"The sushi didn't taste fresh. Had concerns about food safety.",
"Artistic plating, but flavors didn't quite harmonize.",
"Transport yourself to Spain with this authentic tapas experience!",
"Greasy, heavy food. Left feeling unwell.",
"Exquisite fine dining. Worth every penny of the hefty price tag.",
"Another cookie-cutter franchise restaurant. Nothing unique.",
"The seasonal special was a letdown. Stick to the regular menu.",
"Intimate setting perfect for a special occasion.",
"Dried out chicken and mushy vegetables. Amateur cooking at best.",
"Sommelier's wine pairing elevated the entire meal.",
"Interminable wait times. Good food can't make up for poor service.",
"Innovative plant-based dishes that could convert any carnivore.",
"Ridiculously small portions. More of a snack than a meal.",
"Superb seafood. You can taste the ocean freshness.",
"Uninspired menu. Felt like I could make better food at home.",
"Incredible selection of gluten-free and allergen-free options.",
"Uncomfortable chairs and tepid food. Not a pleasant experience.",
"The buffet offered an impressive variety of high-quality dishes.",
"All flash, no substance. Prioritized appearance over taste.",
"Comfort food at its finest. Like a warm hug for your taste buds.",
"Poorly trained staff and disorganized service ruined our night.",
"A symphony of flavors. The chef is truly a culinary artist.",
"The food was okay, but nothing memorable.",
"Finally, a restaurant that takes dietary restrictions seriously!",
"Overhyped and overpriced. Left feeling disappointed and ripped off.",
"Expertly crafted cocktails complemented the innovative menu.",
"Mediocre food, but the live music made up for it.",
"Abysmal service and even worse food. A total waste of money.",
"The tasting menu was a delightful journey through local cuisine.",
"Slightly pricey, but the quality mostly justified the cost.",
"Beautiful venue, but the food didn't live up to expectations.",
"Quick, tasty, and affordable. Perfect for a casual meal.",
"More style than substance. Felt like eating at an Instagram post.",
"Quaint bistro with simple yet delicious traditional recipes.",
"Unremarkable food and forgettable atmosphere. Won't be back."
]

# Labels: 2 for positive, 1 for neutral, 0 for negative
labels = [
    2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
    0, 1, 2, 0, 1, 0, 1, 2, 0, 2,
    1, 0, 2, 0, 2, 0, 2, 0, 2, 0,
    2, 0, 2, 0, 2, 0, 2, 1, 2, 0,
    2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
    2, 0, 1, 0, 1, 0, 1, 0, 2, 0,
    1, 0, 2, 0, 2, 0, 1, 0, 2, 0,
    2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
    1, 0, 1, 0, 2, 0, 2, 0, 1, 0,
    2, 0, 1, 0, 2, 0, 2, 0, 2, 0,
    2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
    0, 1, 1, 0, 1, 0, 1, 2, 0, 2,
    1, 0, 1, 0, 2, 0, 2, 0, 2, 0,
    2, 0, 2, 0, 2, 0, 2, 1, 2, 0,
    2, 1, 0, 2, 1, 1, 2, 0, 2, 1,
    2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
    0, 1, 1, 0, 1, 0, 1, 2, 0, 2,
    1, 0, 2, 0, 2, 0, 2, 0, 2, 0,
    2, 0, 2, 0, 2, 0, 2, 1, 2, 0,
    2, 1, 0, 2, 1, 1, 2, 0, 2, 0
]




